### PR TITLE
Added 1st AMO perf script

### PR DESCRIPTION
**Pull request by stupchiy**
should be running on 2.5 jmeter version plus copy /lib dir inside jmeter folder

### CODE REVIEW

**Comment by zacc** [comment]
Hi chuck, not sure about including the plugins binary in the repo. Davehunt would prefer to keep the repo size down. Is it something that can be listed as a requirement and downloaded fairly easily?

**Comment by ghost** [comment]
Agree, should be removed and listed as requirement in README
chuck (@stupchiy)

**Comment by stephendonner** [comment]
I'm on JMeter 2.5, and get this error even when the plugin is in lib/ext:

http://pastebin.mozilla.org/1584802

2012/04/20 16:17:55 INFO  - jmeter.save.SaveService: All converter versions present and correct
2012/04/20 16:17:55 ERROR - jmeter.save.SaveService: Conversion error com.thoughtworks.xstream.converters.ConversionException: HTTPSamplerProxy : HTTPSamplerProxy : HTTPSamplerProxy : HTTPSamplerProxy
---- Debugging information ----
message             : HTTPSamplerProxy : HTTPSamplerProxy
cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassException
cause-message       : HTTPSamplerProxy : HTTPSamplerProxy
class               : org.apache.jorphan.collections.ListedHashTree
required-type       : org.apache.jorphan.collections.ListedHashTree
path                : /jmeterTestPlan/hashTree/hashTree/hashTree[2]/hashTree/HTTPSamplerProxy
line number         : 68

...

**Comment by stupchiy** [comment]
@stephendonner seems you was running on 2.4 version, cause I can see such kind of messages in your pastebin /Applications/jakarta-jmeter-2.4/bin/user.properties

**Comment by stephendonner** [comment]
@stupchiy @zacc and I both had the same issue; I upgraded my 2.4 binary with the 2.5 one (copied over the changed core files).  I'll try again with a clean install, though @zacc was always running a completely fresh 2.5 one.

**Comment by stupchiy** [comment]
@stephendonner @zacc , did you copied lib in jmeter folder (/lib/ext/JMeterPlugins.jar) ? Cause I just tried on couple different PC's (mostly linux) and was working just fine. Thanks...let me know

**Comment by stephendonner** [comment]
Got it working now; will take a closer look today + tomorrow, then report back!

**Comment by stephendonner** [comment]
Sorry this took so, so long; it's obvious that performance is a little tough for us to get a concerted effort on right now (makes it complicated that between IT + product, we're not sure _exactly_ what we need).  Merging this in -- it's certainly very useful, and deserves inclusion.  Thanks again, @stupchiy!

**Pull request merged**
